//! The scrolling and scrollbar setters of the `TuiStyle` builder:
//! `scrollbar-*`, `overscroll-behavior-*`, `scroll-padding-*`,
//! `scroll-margin-*`, `scroll-behavior`.

use super::super::{ImportantMask, TuiStyle};
use crate::Value;

impl TuiStyle {
    setter!(
        "scrollbar-gutter",
        scrollbar_gutter,
        scrollbar_gutter,
        scrollbar_gutter_important,
        SCROLLBAR_GUTTER,
        crate::layout::ScrollbarGutter
    );
    setter!(
        "scrollbar-width",
        scrollbar_width,
        scrollbar_width,
        scrollbar_width_important,
        SCROLLBAR_WIDTH,
        crate::layout::ScrollbarWidth
    );
    setter!(
        "scrollbar-color",
        scrollbar_color,
        scrollbar_color,
        scrollbar_color_important,
        SCROLLBAR_COLOR,
        crate::layout::ScrollbarColor
    );
    setter!(
        "overscroll-behavior-x",
        overscroll_behavior_x,
        overscroll_behavior_x,
        overscroll_behavior_x_important,
        OVERSCROLL_BEHAVIOR_X,
        crate::layout::OverscrollBehavior
    );
    setter!(
        "overscroll-behavior-y",
        overscroll_behavior_y,
        overscroll_behavior_y,
        overscroll_behavior_y_important,
        OVERSCROLL_BEHAVIOR_Y,
        crate::layout::OverscrollBehavior
    );
    setter!(
        "scroll-padding-top",
        scroll_padding_top,
        scroll_padding_top,
        scroll_padding_top_important,
        SCROLL_PADDING_TOP,
        crate::layout::ScrollPadding
    );
    setter!(
        "scroll-padding-right",
        scroll_padding_right,
        scroll_padding_right,
        scroll_padding_right_important,
        SCROLL_PADDING_RIGHT,
        crate::layout::ScrollPadding
    );
    setter!(
        "scroll-padding-bottom",
        scroll_padding_bottom,
        scroll_padding_bottom,
        scroll_padding_bottom_important,
        SCROLL_PADDING_BOTTOM,
        crate::layout::ScrollPadding
    );
    setter!(
        "scroll-padding-left",
        scroll_padding_left,
        scroll_padding_left,
        scroll_padding_left_important,
        SCROLL_PADDING_LEFT,
        crate::layout::ScrollPadding
    );
    setter!(
        "scroll-margin-top",
        scroll_margin_top,
        scroll_margin_top,
        scroll_margin_top_important,
        SCROLL_MARGIN_TOP,
        i16
    );
    setter!(
        "scroll-margin-right",
        scroll_margin_right,
        scroll_margin_right,
        scroll_margin_right_important,
        SCROLL_MARGIN_RIGHT,
        i16
    );
    setter!(
        "scroll-margin-bottom",
        scroll_margin_bottom,
        scroll_margin_bottom,
        scroll_margin_bottom_important,
        SCROLL_MARGIN_BOTTOM,
        i16
    );
    setter!(
        "scroll-margin-left",
        scroll_margin_left,
        scroll_margin_left,
        scroll_margin_left_important,
        SCROLL_MARGIN_LEFT,
        i16
    );
    setter!(
        "scroll-behavior",
        scroll_behavior,
        scroll_behavior,
        scroll_behavior_important,
        SCROLL_BEHAVIOR,
        crate::layout::ScrollBehavior
    );
    setter!(
        "scroll-snap-type",
        scroll_snap_type,
        scroll_snap_type,
        scroll_snap_type_important,
        SCROLL_SNAP_TYPE,
        crate::layout::ScrollSnapType
    );
    setter!(
        "scroll-snap-align",
        scroll_snap_align,
        scroll_snap_align,
        scroll_snap_align_important,
        SCROLL_SNAP_ALIGN,
        crate::layout::ScrollSnapAlign
    );
    setter!(
        "scroll-snap-stop",
        scroll_snap_stop,
        scroll_snap_stop,
        scroll_snap_stop_important,
        SCROLL_SNAP_STOP,
        crate::layout::ScrollSnapStop
    );
}
